import type { Metadata } from 'next'

import './globals.scss'

import React from 'react'
import Navbar from '@/components/molecules/NavBar/NavBar'
import Footer from '@/components/molecules/Footer/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
